module.exports = {
  // Application
  APPLICATION_VERSION: "3.0.1",
  APPLICATION_QUIT: "application-quit",
  HANDLE_APPLICATION_QUIT: "handle-application-quit",
  SHOW_WAIT_WINDOW: "show-wait-window",
  HIDE_WAIT_WINDOW: "hide-wait-window",
  // ACI
  ACI_FETCH_LATEST_FIRMWARE_VERSION: "aci-fetch-latest-firmware-version",
  HANDLE_ACI_FETCH_LATEST_FIRMWARE_VERSION: "handle-aci-fetch-latest-firmware-version",
  ACI_FETCH_ALL_FIRMWARE_VERSION: "aci-fetch-all-firmware-version",
  HANDLE_ACI_FETCH_ALL_FIRMWARE_VERSION: "handle-aci-fetch-all-firmware-version",
  ACI_FETCH_PLATFORM_FIRMWARE_VERSION: "aci-fetch-platform-firmware-version",
  HANDLE_ACI_FETCH_PLATFORM_FIRMWARE_VERSION: "handle-aci-fetch-platform-firmware-version",
  ACI_QUERY_TENANT_NAME_EXISTS: "aci-query-tenant-name-exists",
  HANDLE_ACI_QUERY_TENANT_NAME_EXISTS: "handle-aci-query-tenant-name-exists"
};

// APPLICATION_VERSION, APPLICATION_QUIT, HANDLE_APPLICATION_QUIT, SHOW_WAIT_WINDOW, HIDE_WAIT_WINDOW, ACI_FETCH_LATEST_FIRMWARE_VERSION, HANDLE_ACI_FETCH_LATEST_FIRMWARE_VERSION, ACI_FETCH_ALL_FIRMWARE_VERSION, HANDLE_ACI_FETCH_ALL_FIRMWARE_VERSION, ACI_FETCH_PLATFORM_FIRMWARE_VERSION, HANDLE_ACI_FETCH_PLATFORM_FIRMWARE_VERSION, ACI_QUERY_TENANT_NAME_EXISTS, HANDLE_ACI_QUERY_TENANT_NAME_EXISTS
